### ISSUE TITLE
Error:Error: Duplicate resources

### ISSUE THREAD

**Issue by LeoYe168** [Zellius/android-shortcut-gradle-plugin#2]
build/generated/res/resValues/D21/debug/xml/shortcuts.xml: Error: Duplicate resources

**Comment by Zellius** [comment]
@LeoYe168 Hi! Can you provide your app.gradle file? If you store your source **shortcuts.xml** inside **xml** folder, try to put it somewhere else and set path to it.

**Comment by LeoYe168** [comment]
yes, i put it in res folder,   and  solve it

**Comment by Zellius** [comment]
Nice to hear it =)
